model_path: openai_compat://my-model
data_path: miniwob://v1
baseline: baselines/miniwob.json
metric: success_rate

benchmark: miniwob
docker_image: autorl-bench/eval-miniwob:0.1

model:
  provider: openai_compat
  base_url: http://host.docker.internal:8000/v1
  api_key: EMPTY
  temperature: 0.2
  max_tokens: 512

params:
  task_set:
    - click-button
    - click-link
    - click-menu
  episodes_per_task: 10
  max_steps: 30
  seed: 123
  action_space: liu18

stages:
  - entry: "python /app/env_entry.py eval --scenario /scenario.yaml --output /output"
    network: host
